server:
  port: 8081

spring:
  application:
    name: order-service
  mvc:
    servlet:
      path: /orders
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

