events {}

http {

    upstream frontend1 {
        server frontend-1:80;
    }

    upstream frontend2 {
        server frontend-2:80;
    }

    upstream gateway {
        server gateway-service:8080;
    }

    # -----------------------------
    # HTTP → HTTPS Redirect
    # -----------------------------
    server {
        listen 80;

        return 301 https://$host$request_uri;
    }

    server {
       # listen 80;

        listen 443 ssl;

        # SSL Certificates
        ssl_certificate /etc/nginx/ssl/fullchain.pem;
        ssl_certificate_key /etc/nginx/ssl/privkey.pem;

        # Modern TLS versions
        ssl_protocols TLSv1.2 TLSv1.3;


         # ---------------- FRONTEND ----------------
        location /app1/ {
            proxy_pass http://frontend1/;
        }

        location /app2/ {
            proxy_pass http://frontend2/;
        }

        # ---------------- BACKEND (API Gateway) ----------------

        location / {
            proxy_pass http://gateway/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}