events {}

http {

    upstream frontend1 {
        server frontend-1:80;
    }

    upstream frontend2 {
        server frontend-2:80;
    }

    server {
        listen 80;

        # Route by path
        location /app1/ {
            proxy_pass http://frontend1/;
        }

        location /app2/ {
            proxy_pass http://frontend2/;
        }
    }
}